// remotemessage.proto
syntax = "proto3";
package remote;
option java_multiple_files = true;

message RemoteAppLinkLaunchRequest { string app_link = 1; }
message RemoteResetPreferredAudioDevice {}
message RemoteSetPreferredAudioDevice {}
message RemoteAdjustVolumeLevel {}
message RemoteSetVolumeLevel {}
message RemoteStartScan {}
message RemoteStopScan {}
message RemoteConnect {}
message RemoteDisconnect {}
message RemoteError {}
message RemoteImeBatchEdit {}
message RemoteImeKeyEvent {}
message RemoteImeShowRequest {}
message RemoteImeHideRequest {}
message RemoteImeTextFieldStatus {}
message RemoteImeSetComposingText {}
message RemoteImeAction {}
message RemoteVoiceBegin {}
message RemoteVoicePayload {}
message RemoteVoiceEnd {}
message RemoteStart {}
message RemoteStop {}

message RemoteKeyInject {
  enum Direction { UNKNOWN = 0; START = 1; END = 2; SHORT = 3; }
  int32 key_code = 1;
  Direction direction = 2;
}

message RemoteKeyCode {
  enum KeyCode {
    UNKNOWN = 0;
    KEYCODE_UNKNOWN = 1;
    KEYCODE_HOME = 3;
    KEYCODE_BACK = 4;
    KEYCODE_DPAD_UP = 19;
    KEYCODE_DPAD_DOWN = 20;
    KEYCODE_DPAD_LEFT = 21;
    KEYCODE_DPAD_RIGHT = 22;
    KEYCODE_DPAD_CENTER = 23;
    KEYCODE_VOLUME_UP = 24;
    KEYCODE_VOLUME_DOWN = 25;
    KEYCODE_POWER = 26;
    KEYCODE_MUTE = 164;
    KEYCODE_MEDIA_PLAY_PAUSE = 85;
  }
}

message RemoteConfigure { int32 code1 = 1; RemoteDeviceInfo device_info = 2; }
message RemoteDeviceInfo {
  string model = 1; string vendor = 2; int32 unknown1 = 3;
  string unknown2 = 4; string package_name = 5; string app_version = 6;
}
message RemoteSetActive { int32 active = 1; }
message RemotePingRequest { int32 val1 = 1; }
message RemotePingResponse { int32 val1 = 1; }

message RemoteMessage {
  oneof message {
    RemoteAppLinkLaunchRequest remote_app_link_launch_request = 1;
    RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 2;
    RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 3;
    RemoteAdjustVolumeLevel remote_adjust_volume_level = 4;
    RemoteSetVolumeLevel remote_set_volume_level = 5;
    RemoteStartScan remote_start_scan = 6;
    RemoteStopScan remote_stop_scan = 7;
    RemoteConnect remote_connect = 8;
    RemoteDisconnect remote_disconnect = 9;
    RemoteError remote_error = 10;
    RemoteImeBatchEdit remote_ime_batch_edit = 11;
    RemoteImeKeyEvent remote_ime_key_event = 12;
    RemoteImeShowRequest remote_ime_show_request = 13;
    RemoteImeHideRequest remote_ime_hide_request = 14;
    RemoteImeTextFieldStatus remote_ime_text_field_status = 15;
    RemoteImeSetComposingText remote_ime_set_composing_text = 16;
    RemoteImeAction remote_ime_action = 17;
    RemoteVoiceBegin remote_voice_begin = 18;
    RemoteVoicePayload remote_voice_payload = 19;
    RemoteVoiceEnd remote_voice_end = 20;
    RemoteStart remote_start = 21;
    RemoteStop remote_stop = 22;
    RemoteKeyInject remote_key_inject = 23;
    RemoteConfigure remote_configure = 24;
    RemoteSetActive remote_set_active = 25;
    RemotePingRequest remote_ping_request = 26;
    RemotePingResponse remote_ping_response = 27;
  }
}